resources:
  pipelines:
    pipeline_dlt_curated_layer:
      name: DLT Curated Layer
      libraries:
        - glob:
            include: ../../src/gold/DLT
              Curated Layer/transformations/**
      schema: gold
      photon: true
      catalog: musicstreaming_project
      serverless: true
      root_path: ../../musicstreaming_dab/src/gold/DLT
        Curated Layer
